INSERT INTO productDB.customer (id, name, address) VALUES (1, 'naruto', 'Konoha');
INSERT INTO productDB.customer (id, name, address) VALUES (2, 'sasuke', 'Konoha');
INSERT INTO productDB.customer (id, name, address) VALUES (3, 'sakura', 'Konoha');
INSERT INTO productDB.customer (id, name, address) VALUES (4, 'kakashi', 'Konoha');
INSERT INTO productDB.customer (id, name, address) VALUES (5, 'lee', 'Konoha');
INSERT INTO productDB.customer (id, name, address) VALUES (6, 'neji', 'Konoha');
INSERT INTO productDB.customer (id, name, address) VALUES (7, 'ten-ten', 'Konoha');
INSERT INTO productDB.customer (id, name, address) VALUES (8, 'kiba', 'Konoha');
INSERT INTO productDB.customer (id, name, address) VALUES (9, 'shino', 'Konoha');
INSERT INTO productDB.customer (id, name, address) VALUES (10, 'hinata', 'Konoha');
INSERT INTO productDB.customer (id, name, address) VALUES (11, 'shikamaru', 'Konoha');
INSERT INTO productDB.customer (id, name, address) VALUES (12, 'chouji', 'Konoha');
INSERT INTO productDB.customer (id, name, address) VALUES (13, 'ino', 'Konoha');
INSERT INTO productDB.customer (id, name, address) VALUES (14, 'asuma', 'Konoha');
INSERT INTO productDB.customer (id, name, address) VALUES (15, 'kurenai', 'Konoha');
INSERT INTO productDB.customer (id, name, address) VALUES (16, 'Guy', 'Konoha');
INSERT INTO productDB.customer (id, name, address) VALUES (17, 'Sarutobi', 'Konoha');
INSERT INTO productDB.customer (id, name, address) VALUES (18, 'Orochimaru', 'Konoha');
INSERT INTO productDB.customer (id, name, address) VALUES (19, 'Kabuto', 'Konoha');
INSERT INTO productDB.customer (id, name, address) VALUES (20, 'iruka', 'Konoha');
INSERT INTO productDB.customer (id, name, address) VALUES (21, 'konohamaru', 'Konoha');
INSERT INTO productDB.customer (id, name, address) VALUES (22, 'gaara', 'Suna');
INSERT INTO productDB.customer (id, name, address) VALUES (23, 'temari', 'Suna');
INSERT INTO productDB.customer (id, name, address) VALUES (24, 'kankuro', 'Suna');
INSERT INTO productDB.customer (id, name, address) VALUES (25, 'luffy', 'one piece');
INSERT INTO productDB.customer (id, name, address) VALUES (26, 'zoro', 'one piece');
INSERT INTO productDB.customer (id, name, address) VALUES (27, 'nami', 'one piece');
INSERT INTO productDB.customer (id, name, address) VALUES (28, 'usopp', 'one piece');
INSERT INTO productDB.customer (id, name, address) VALUES (29, 'sanji', 'one piece');
INSERT INTO productDB.customer (id, name, address) VALUES (30, 'chopper', 'one piece');
INSERT INTO productDB.customer (id, name, address) VALUES (31, 'robin', 'one piece');
INSERT INTO productDB.customer (id, name, address) VALUES (32, 'franky', 'one piece');
INSERT INTO productDB.customer (id, name, address) VALUES (33, 'brook', 'one piece');
INSERT INTO productDB.customer (id, name, address) VALUES (34, 'jinbe', 'one piece');
